-- Estrutura mínima esperada pelo site e pelo aplicativo.
-- Pode ser executado no SQL Editor do projeto xllbpyihfjfmtbzcrihs.

create table if not exists public.lixeiras (
    id bigint generated by default as identity primary key,
    nome text not null,
    localizacao text,
    altura_cm numeric not null default 50
);

create table if not exists public.leituras (
    id bigint generated by default as identity primary key,
    lixeira_id bigint not null references public.lixeiras(id) on delete cascade,
    percentual_cheio numeric not null check (percentual_cheio >= 0 and percentual_cheio <= 100),
    criado_em timestamptz not null default now()
);

create index if not exists idx_leituras_lixeira_data
    on public.leituras (lixeira_id, criado_em desc);

alter table public.lixeiras enable row level security;
alter table public.leituras enable row level security;

grant select on table public.lixeiras to anon, authenticated;
grant select, insert on table public.leituras to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

do $$
begin
    if not exists (
        select 1 from pg_policies
        where schemaname = 'public' and tablename = 'lixeiras' and policyname = 'leitura_publica_lixeiras'
    ) then
        create policy leitura_publica_lixeiras
            on public.lixeiras
            for select
            to anon, authenticated
            using (true);
    end if;

    if not exists (
        select 1 from pg_policies
        where schemaname = 'public' and tablename = 'leituras' and policyname = 'leitura_publica_leituras'
    ) then
        create policy leitura_publica_leituras
            on public.leituras
            for select
            to anon, authenticated
            using (true);
    end if;

    if not exists (
        select 1 from pg_policies
        where schemaname = 'public' and tablename = 'leituras' and policyname = 'insercao_publica_leituras'
    ) then
        create policy insercao_publica_leituras
            on public.leituras
            for insert
            to anon, authenticated
            with check (
                percentual_cheio >= 0
                and percentual_cheio <= 100
                and exists (
                    select 1 from public.lixeiras l
                    where l.id = lixeira_id
                )
            );
    end if;
end $$;

do $$
begin
    if not exists (
        select 1
        from pg_publication_tables
        where pubname = 'supabase_realtime'
          and schemaname = 'public'
          and tablename = 'leituras'
    ) then
        alter publication supabase_realtime add table public.leituras;
    end if;
end $$;
